version: "2"
services:
  react:
    image: "node:8"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    expose:
      - "3000"
    ports:
      - "80:3000"
    command: "npm start"

networks:
  default:
    external:
      name: warbler_backend_default
