version: "2"
services:
  front:
    image: "adamdenoon/todos_frontend:latest"
    user: "node"
    environment:
      - NODE_ENV=production
    expose:
      - "8080"
    ports:
      - "80:8080"
    command: "node index.js"
    links:
      - back
    restart: always
  back:
    image: "adamdenoon/todos_backend:latest"
    user: "node"
    environment:
      - NODE_ENV=production
    expose:
      - "8081"
    ports:
      - "8080:8081"
    command: "node index.js"
    links:
      - mongo
    restart: always
  mongo:
    image: mongo
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodata:
